apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  generateName: crossplane-bucket-
  name: test-bytommy28
spec:
  forProvider:
    region: ap-southeast-1
  providerConfigRef:
    name: default
